# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rover.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"\x1e\n\nMapRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\";\n\x08MapReply\x12\x10\n\x08json_map\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"\"\n\x0e\x43ommandRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"\x16\n\x07\x43ommand\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\"$\n\x11MineSerialRequest\x12\x0f\n\x07mine_id\x18\x01 \x01(\t\"0\n\x0fMineSerialReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0e\n\x06serial\x18\x02 \x01(\t2\xc3\x01\n\rGroundControl\x12,\n\x06GetMap\x12\x11.rover.MapRequest\x1a\x0f.rover.MapReply\x12;\n\x10GetCommandStream\x12\x15.rover.CommandRequest\x1a\x0e.rover.Command0\x01\x12G\n\x13GetMineSerialNumber\x12\x18.rover.MineSerialRequest\x1a\x16.rover.MineSerialReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=22
  _globals['_MAPREQUEST']._serialized_end=52
  _globals['_MAPREPLY']._serialized_start=54
  _globals['_MAPREPLY']._serialized_end=113
  _globals['_COMMANDREQUEST']._serialized_start=115
  _globals['_COMMANDREQUEST']._serialized_end=149
  _globals['_COMMAND']._serialized_start=151
  _globals['_COMMAND']._serialized_end=173
  _globals['_MINESERIALREQUEST']._serialized_start=175
  _globals['_MINESERIALREQUEST']._serialized_end=211
  _globals['_MINESERIALREPLY']._serialized_start=213
  _globals['_MINESERIALREPLY']._serialized_end=261
  _globals['_GROUNDCONTROL']._serialized_start=264
  _globals['_GROUNDCONTROL']._serialized_end=459
# @@protoc_insertion_point(module_scope)
