# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rover_pb2 as rover__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rover_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroundControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/rover.GroundControl/GetMap',
                request_serializer=rover__pb2.MapRequest.SerializeToString,
                response_deserializer=rover__pb2.MapResponse.FromString,
                _registered_method=True)
        self.StreamCommands = channel.unary_stream(
                '/rover.GroundControl/StreamCommands',
                request_serializer=rover__pb2.CommandRequest.SerializeToString,
                response_deserializer=rover__pb2.CommandChunk.FromString,
                _registered_method=True)
        self.GetMineSerial = channel.unary_unary(
                '/rover.GroundControl/GetMineSerial',
                request_serializer=rover__pb2.MineSerialRequest.SerializeToString,
                response_deserializer=rover__pb2.MineSerialResponse.FromString,
                _registered_method=True)
        self.ReportExecution = channel.unary_unary(
                '/rover.GroundControl/ReportExecution',
                request_serializer=rover__pb2.ExecutionReport.SerializeToString,
                response_deserializer=rover__pb2.Ack.FromString,
                _registered_method=True)
        self.ShareMinePin = channel.unary_unary(
                '/rover.GroundControl/ShareMinePin',
                request_serializer=rover__pb2.MinePin.SerializeToString,
                response_deserializer=rover__pb2.Ack.FromString,
                _registered_method=True)


class GroundControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareMinePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroundControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rover__pb2.MapRequest.FromString,
                    response_serializer=rover__pb2.MapResponse.SerializeToString,
            ),
            'StreamCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=rover__pb2.CommandRequest.FromString,
                    response_serializer=rover__pb2.CommandChunk.SerializeToString,
            ),
            'GetMineSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerial,
                    request_deserializer=rover__pb2.MineSerialRequest.FromString,
                    response_serializer=rover__pb2.MineSerialResponse.SerializeToString,
            ),
            'ReportExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportExecution,
                    request_deserializer=rover__pb2.ExecutionReport.FromString,
                    response_serializer=rover__pb2.Ack.SerializeToString,
            ),
            'ShareMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareMinePin,
                    request_deserializer=rover__pb2.MinePin.FromString,
                    response_serializer=rover__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rover.GroundControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rover.GroundControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroundControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/GetMap',
            rover__pb2.MapRequest.SerializeToString,
            rover__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rover.GroundControl/StreamCommands',
            rover__pb2.CommandRequest.SerializeToString,
            rover__pb2.CommandChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMineSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/GetMineSerial',
            rover__pb2.MineSerialRequest.SerializeToString,
            rover__pb2.MineSerialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/ReportExecution',
            rover__pb2.ExecutionReport.SerializeToString,
            rover__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/ShareMinePin',
            rover__pb2.MinePin.SerializeToString,
            rover__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
