# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rover.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"\x1e\n\nMapRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"\\\n\x0bMapResponse\x12\x0c\n\x04rows\x18\x01 \x03(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07start_x\x18\x04 \x01(\x05\x12\x0f\n\x07start_y\x18\x05 \x01(\x05\"\"\n\x0e\x43ommandRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\".\n\x0c\x43ommandChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\";\n\x11MineSerialRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"D\n\x12MineSerialResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0e\n\x06serial\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"N\n\x07MinePin\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\x0e\n\x06serial\x18\x04 \x01(\t\x12\x0b\n\x03pin\x18\x05 \x01(\t\"\xac\x01\n\x0f\x45xecutionReport\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x10\n\x08\x65xploded\x18\x03 \x01(\x08\x12\x16\n\x0e\x63ommands_total\x18\x04 \x01(\x05\x12\x19\n\x11\x63ommands_executed\x18\x05 \x01(\x05\x12\x0f\n\x07\x66inal_x\x18\x06 \x01(\x05\x12\x0f\n\x07\x66inal_y\x18\x07 \x01(\x05\x12\x0f\n\x07message\x18\x08 \x01(\t\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa9\x02\n\rGroundControl\x12/\n\x06GetMap\x12\x11.rover.MapRequest\x1a\x12.rover.MapResponse\x12>\n\x0eStreamCommands\x12\x15.rover.CommandRequest\x1a\x13.rover.CommandChunk0\x01\x12\x44\n\rGetMineSerial\x12\x18.rover.MineSerialRequest\x1a\x19.rover.MineSerialResponse\x12\x35\n\x0fReportExecution\x12\x16.rover.ExecutionReport\x1a\n.rover.Ack\x12*\n\x0cShareMinePin\x12\x0e.rover.MinePin\x1a\n.rover.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=22
  _globals['_MAPREQUEST']._serialized_end=52
  _globals['_MAPRESPONSE']._serialized_start=54
  _globals['_MAPRESPONSE']._serialized_end=146
  _globals['_COMMANDREQUEST']._serialized_start=148
  _globals['_COMMANDREQUEST']._serialized_end=182
  _globals['_COMMANDCHUNK']._serialized_start=184
  _globals['_COMMANDCHUNK']._serialized_end=230
  _globals['_MINESERIALREQUEST']._serialized_start=232
  _globals['_MINESERIALREQUEST']._serialized_end=291
  _globals['_MINESERIALRESPONSE']._serialized_start=293
  _globals['_MINESERIALRESPONSE']._serialized_end=361
  _globals['_MINEPIN']._serialized_start=363
  _globals['_MINEPIN']._serialized_end=441
  _globals['_EXECUTIONREPORT']._serialized_start=444
  _globals['_EXECUTIONREPORT']._serialized_end=616
  _globals['_ACK']._serialized_start=618
  _globals['_ACK']._serialized_end=652
  _globals['_GROUNDCONTROL']._serialized_start=655
  _globals['_GROUNDCONTROL']._serialized_end=952
# @@protoc_insertion_point(module_scope)
